Update fixtures
Updated fixtures with DataFrame representations of the tables in the test database
to use string values for data types instead of pandas data types. E.g. change
pd.Int16Dtype to 'int16' in the dtypes dictionary. This was done to avoid raising exception
"AttributeError: 'BooleanArray' object has no attribute 'sum'" when using pandas read_csv
function to create the DataFrames. Specifying pandas integer data types casued this issue,
which started appearing in pandas >= 1.3.0.
This exception is not raised when specifying data types as strings or using numpy data types
e.g. np.int16. Using pd.StringDtype() still works.

Added keyword arguments to all parameters of calls to pandas read_csv function in the fixtures.
read_csv will require keyword only arguments in future versions of
pandas.